esphome:
  name: delumo-esp-idf

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    version: recommended

external_components:
  - source:
      type: local
      path: components

logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "Zyxel Dem"
  password: "kotomur1"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Delumo-Isp-Idf Fallback Hotspot"
    password: "Nguk2yTc5s13"

captive_portal:

light:
  #ГОСТИНАЯ
  - platform: delumo
    name: "hall_aux"
    serial: 0x0850
    output: delumo_spi

  - platform: delumo
    name: "hall_main"
    serial: 0x0851
    output: delumo_spi

  #ПРИХОЖАЯ
  - platform: delumo
    name: "entrance"
    serial: 0x086A
    output: delumo_spi

  #ВАННАЯ
  - platform: delumo
    name: "bathroom_aux"
    serial: 0x085B
    output: delumo_spi

  - platform: delumo
    name: "bathroom_main"
    serial: 0x085A
    output: delumo_spi

  #КУХНЯ
  - platform: delumo
    name: "kitchen_main"
    serial: 0x0854
    output: delumo_spi

  - platform: delumo
    name: "kitchen_aux"
    serial: 0x0853
    output: delumo_spi

  - platform: delumo
    name: "kitchen_work"
    serial: 0x08D9
    output: delumo_spi

  #КЛАДОВКА
  - platform: delumo
    name: "closet"
    serial: 0x08D8
    output: delumo_spi

  #ДЕТСКАЯ
  - platform: delumo
    name: "kidsroom_main"
    serial: 0x0856
    output: delumo_spi

  - platform: delumo
    name: "kidsroom_aux"
    serial: 0x0857
    output: delumo_spi

  #СПАЛЬНЯ
  - platform: delumo
    name: "bedroom_main"
    serial: 0x0858
    output: delumo_spi

  - platform: delumo
    name: "bedroom_aux"
    serial: 0x0859
    output: delumo_spi

output:
  - platform: delumo
    id: delumo_spi
    cs_pin: GPIO5
    fsel_pin: GPIO21 #17
    reset_pin: GPIO17 #21
    mosi_pin: GPIO23
    miso_pin: GPIO19
    clk_pin: GPIO18
