esphome:
  name: delumo-esp-idf

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    version: recommended

external_components:
  - source:
      type: local
      path: components

# Enable logging
logger:
  level: INFO
# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "Zyxel Dem"
  password: "kotomur1"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Delumo-Isp-Idf Fallback Hotspot"
    password: "Nguk2yTc5s13"

captive_portal:

light:
  #ГОСТИНАЯ
  - platform: delumo
    name: "hall_aux"
    serial: 0x0850
    output: delumo_spi

spi:
  mosi_pin: GPIO23
  miso_pin: GPIO19
  clk_pin: GPIO18
  # id: spi_1
  # interface: spi3

output:
  - platform: delumo
    cs_pin: GPIO5 #maybe 22
    fsel_pin: GPIO17
    reset_pin: GPIO21
    id: delumo_spi
    # spi_id: spi_1
