esphome:
  name: delumo-esp-idf

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    version: recommended

external_components:
  - source:
      type: local
      path: components

logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "Zyxel Dem"
  password: "kotomur1"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Delumo-Isp-Idf Fallback Hotspot"
    password: "Nguk2yTc5s13"

captive_portal:

light:
  #ГОСТИНАЯ
  - platform: delumo
    name: "hall_aux"
    serial: 0x0850
    output: delumo_spi
  - platform: delumo
    name: "entrance"
    serial: 0x086A
    output: delumo_spi

output:
  - platform: delumo
    id: delumo_spi
    cs_pin: GPIO5
    fsel_pin: GPIO17
    reset_pin: GPIO21
    mosi_pin: GPIO23
    miso_pin: GPIO19
    clk_pin: GPIO18
